---
# Source: gitops-chart/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: crossplane
---
# Source: gitops-chart/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: drupal-app
---
# Source: gitops-chart/templates/project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: Project dev
  destinations:
    - server: https://kubernetes.default.svc
      namespace: drupal-app
  sourceRepos:
    - https://github.com/qasmi/tdd-developer-platform-demo.git
    - https://charts.bitnami.com/bitnami
  clusterResourceWhitelist: []
---
# Source: gitops-chart/templates/project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Project platform
  destinations:
    - server: https://kubernetes.default.svc
      namespace: crossplane
  sourceRepos:
    - https://github.com/qasmi/tdd-developer-platform-demo.git
    - https://charts.crossplane.io/stable
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: apiregistration.k8s.io
      kind: APIService
    - group: scheduling.k8s.io
      kind: PriorityClass
---
# Source: gitops-chart/templates/applicationSet.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations: {}
  name: dev-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/qasmi/tdd-developer-platform-demo.git
        revision: HEAD
        files:
          - path: "demo-cluster/team-dev/apps.yaml"
  template:
    metadata:
      name: '{{ .name }}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .syncWave | default "10" }}'
      finalizers:
        - "resources-finalizer.argocd.argoproj.io"
    spec:
      project: '{{ .project }}'
      revisionHistoryLimit: 3
      sources:
      - repoURL: https://github.com/qasmi/tdd-developer-platform-demo.git
        targetRevision: HEAD
        ref: valuesRef
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
  templatePatch: |
    spec:
      sources:
        - chart: '{{ .chart }}'
          repoURL: '{{ .repo }}'
          targetRevision: '{{ .version }}'
          helm:
            valueFiles:
            {{- range .valueFiles }}
              - $valuesRef/demo-cluster/team-dev/values/{{ . }}
            {{- end }}
        - repoURL: 'https://github.com/qasmi/tdd-developer-platform-demo.git'
          targetRevision: 'HEAD'
          path: demo-cluster/team-dev/values
          ref: valuesRef
    {{- if .autoSync }}
      syncPolicy:
        automated:
          prune: {{ .autoSync.enabled }}
          selfHeal: {{ .autoSync.enabled }}
        {{- if .autoSync.syncOptions }}
        syncOptions:
        {{- range .autoSync.syncOptions }}
          - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}
    {{- if .ignoreDifferences }}
      ignoreDifferences:
    {{- range .ignoreDifferences }}
      - group: {{ .group }}
        kind: {{ .kind }}
        {{- if .name }}
        name: {{ .name }}
        {{- end }}
        {{- if .namespace }}
        namespace: {{ .namespace }}
        {{- end }}
        {{- if .jsonPointers }}
        jsonPointers:
        {{- range .jsonPointers }}
          - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .jqPathExpressions }}
        jqPathExpressions:
        {{- range .jqPathExpressions }}
          - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}
    {{- end }}
---
# Source: gitops-chart/templates/applicationSet.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations: {}
  name: platform-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/qasmi/tdd-developer-platform-demo.git
        revision: HEAD
        files:
          - path: "demo-cluster/team-platform/apps.yaml"
  template:
    metadata:
      name: '{{ .name }}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .syncWave | default "10" }}'
      finalizers:
        - "resources-finalizer.argocd.argoproj.io"
    spec:
      project: '{{ .project }}'
      revisionHistoryLimit: 3
      sources:
      - repoURL: https://github.com/qasmi/tdd-developer-platform-demo.git
        targetRevision: HEAD
        ref: valuesRef
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
  templatePatch: |
    spec:
      sources:
        - chart: '{{ .chart }}'
          repoURL: '{{ .repo }}'
          targetRevision: '{{ .version }}'
          helm:
            valueFiles:
            {{- range .valueFiles }}
              - $valuesRef/demo-cluster/team-platform/values/{{ . }}
            {{- end }}
        - repoURL: 'https://github.com/qasmi/tdd-developer-platform-demo.git'
          targetRevision: 'HEAD'
          path: demo-cluster/team-platform/values
          ref: valuesRef
    {{- if .autoSync }}
      syncPolicy:
        automated:
          prune: {{ .autoSync.enabled }}
          selfHeal: {{ .autoSync.enabled }}
        {{- if .autoSync.syncOptions }}
        syncOptions:
        {{- range .autoSync.syncOptions }}
          - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}
    {{- if .ignoreDifferences }}
      ignoreDifferences:
    {{- range .ignoreDifferences }}
      - group: {{ .group }}
        kind: {{ .kind }}
        {{- if .name }}
        name: {{ .name }}
        {{- end }}
        {{- if .namespace }}
        namespace: {{ .namespace }}
        {{- end }}
        {{- if .jsonPointers }}
        jsonPointers:
        {{- range .jsonPointers }}
          - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .jqPathExpressions }}
        jqPathExpressions:
        {{- range .jqPathExpressions }}
          - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}
    {{- end }}
