---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: in-cluster-helm
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: in-cluster-kubernetes
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: mariadbinstances.database.kubecon.io
spec:
  scope: Cluster
  group: database.kubecon.io
  names:
    kind: MariaDBInstance
    plural: mariadbinstances
  defaultCompositionRef:
    name: mariadbinstance-composition
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    size:
                      type: string
                    database:
                      type: string
                    username:
                      type: string
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-patch-and-transform:v0.9.1
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mariadbinstance-composition
spec:
  compositeTypeRef:
    apiVersion: database.kubecon.io/v1alpha1
    kind: MariaDBInstance
  writeConnectionSecretToRef:
    name: drupal-db-conn
    namespace: drupal-app
  mode: Pipeline
  pipeline:
    - step: deploy-mariadb
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: mariadb
            base:
              apiVersion: helm.crossplane.io/v1beta1
              kind: Release
              metadata:
                namespace: crossplane
                name: mariadb
              spec:
                providerConfigRef:
                  name: in-cluster-helm
                forProvider:
                  namespace: drupal-app
                  chart:
                    repository: https://charts.bitnami.com/bitnami
                    name: mariadb
                    version: 22.0.0
                  values:
                    image:
                      repository: bitnamilegacy/mariadb
                      tag: "12.0.2-debian-12-r0"
                    auth:
                      rootPassword: root
                      database: exampledb
                      username: user
                      password: superPass123!
                    primary:
                      persistence:
                        enabled: true
                        size: 1Gi

          # add the static secret
          - name: mariadb-secret
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              metadata:
                name: drupal-db-conn
                namespace: drupal-app
              spec:
                providerConfigRef:
                  name: in-cluster-kubernetes
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: Secret
                    metadata:
                      name: drupal-db-conn
                      namespace: drupal-app
                    type: Opaque
                    data:
                      db-password: c3VwZXJQYXNzMTIzIQ==
            connectionDetails:
              - name: db-password
                type: FromConnectionSecretKey
                fromConnectionSecretKey: password
