apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: mariadbinstances.database.kubecon.io
spec:
  scope: Namespaced
  group: database.kubecon.io
  names:
    kind: MariaDBInstance
    plural: mariadbinstances
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    size:
                      type: string
                    database:
                      type: string
                    username:
                      type: string
