
apiVersion: v1
kind: Secret
metadata:
    name: gitops-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: git
    url: https://github.com/qasmi/tdd-developer-platform-demo.git
