{{- range $teamName, $team := .Values.teams }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations: {}
  name: {{ $teamName }}-apps
  namespace: {{ required "argocd.namespace is required" $.Values.argocd.namespace }}
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: {{ $.Values.gitops.repository }}
        revision: {{ $.Values.gitops.revision | default "HEAD" }}
        files:
          - path: "{{ $.Values.environment.name }}/team-{{ $teamName }}/apps.yaml"
  template:
    metadata:
      name: '{{`{{ .name }}`}}'
      namespace: {{ required "argocd.namespace is required" $.Values.argocd.namespace }}
      annotations:
        argocd.argoproj.io/sync-wave: '{{`{{ .syncWave | default "10" }}`}}'
      finalizers:
        - "resources-finalizer.argocd.argoproj.io"
    spec:
      project: '{{`{{ .project }}`}}'
      revisionHistoryLimit: {{ $.Values.gitops.revisionHistoryLimit }}
      sources:
      - repoURL: {{ $.Values.gitops.repository }}
        targetRevision: {{ $.Values.gitops.revision | default "HEAD" }}
        ref: valuesRef
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{ .namespace }}`}}'
  templatePatch: |
    spec:
      sources:
        - chart: '{{`{{ .chart }}`}}'
          repoURL: '{{`{{ .repo }}`}}'
          targetRevision: '{{`{{ .version }}`}}'
          helm:
            valueFiles:
            {{`{{- range .valueFiles }}`}}
              - $valuesRef/{{ $.Values.environment.name }}/team-{{ $teamName }}/values/{{`{{ . }}`}}
            {{`{{- end }}`}}
        - repoURL: '{{ $.Values.gitops.repository }}'
          targetRevision: '{{ $.Values.gitops.revision | default "HEAD" }}'
          path: {{ $.Values.environment.name }}/team-{{ $teamName }}/values
          ref: valuesRef
    {{`{{- if .autoSync }}`}}
      syncPolicy:
        automated:
          prune: {{`{{ .autoSync.enabled }}`}}
          selfHeal: {{`{{ .autoSync.enabled }}`}}
        {{`{{- if .autoSync.syncOptions }}`}}
        syncOptions:
        {{`{{- range .autoSync.syncOptions }}`}}
          - {{`{{ . }}`}}
        {{`{{- end }}`}}
        {{`{{- end }}`}}
    {{`{{- end }}`}}
    {{`{{- if .ignoreDifferences }}`}}
      ignoreDifferences:
    {{`{{- range .ignoreDifferences }}`}}
      - group: {{`{{ .group }}`}}
        kind: {{`{{ .kind }}`}}
        {{`{{- if .name }}`}}
        name: {{`{{ .name }}`}}
        {{`{{- end }}`}}
        {{`{{- if .namespace }}`}}
        namespace: {{`{{ .namespace }}`}}
        {{`{{- end }}`}}
        {{`{{- if .jsonPointers }}`}}
        jsonPointers:
        {{`{{- range .jsonPointers }}`}}
          - {{`{{ . }}`}}
        {{`{{- end }}`}}
        {{`{{- end }}`}}
        {{`{{- if .jqPathExpressions }}`}}
        jqPathExpressions:
        {{`{{- range .jqPathExpressions }}`}}
          - {{`{{ . }}`}}
        {{`{{- end }}`}}
        {{`{{- end }}`}}
    {{`{{- end }}`}}
    {{`{{- end }}`}}
{{- end }}