kubeProxyReplacement: true
k8sServiceHost: kind-control-plane
k8sServicePort: 6443
nodePort: 
  enabled: true

localRedirectPolicy: true
installNoConntrackIptablesRules: false
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.42.0.0/16
    clusterPoolIPv4MaskSize: 24
    autoCreateCiliumPodIPPools: {}
routingMode: native
ipv4NativeRoutingCIDR: 10.42.0.0/16

externalIPs:
  enabled:true
  
autoDirectNodeRoutes: true
l2announcements:
  enabled: true
bgp:
  enabled: false

rolloutCiliumPods: true
bpf:
  masquerade: true

operator:
  enabled: true
  replicas: 1
        
hubble:
  enabled: false
    
gatewayAPI:
  enabled: true

envoy:
  enabled: false
