kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
  podSubnet: "10.42.0.0/16"
  serviceSubnet: "10.43.0.0/16"
nodes:
- role: control-plane
  image: kindest/node:v1.33.2
- role: worker
  image: kindest/node:v1.33.2
