apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: announcement-policy-1
spec:
  externalIPs: false
  loadBalancerIPs: true
  interfaces:
  - ^eth[0-9]+
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist