apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: databases.example.org
spec:
  group: example.org
  names:
    kind: Database
    plural: databases
  claimNames:
    kind: Database
    plural: databases
  defaultCompositionRef:
    name: mariadb-helm-composition
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    storage:
                      type: string
                      default: "1Gi"
                    username:
                      type: string
                    password:
                      type: string
                    database:
                      type: string
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mariadb-helm-composition
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: Database
  resources:
    - name: mariadb
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        spec:
          forProvider:
            chart:
              name: mariadb
              repository: https://charts.bitnami.com/bitnami
              version: "12.3.0"
            namespace: default
            values:
              image:
                repository: bitnamilegacy/external-dns
              auth:
                username: user
                password: pass
                database: mydb
              primary:
                persistence:
                  size: 1Gi
      patches:
        - fromFieldPath: "metadata.namespace"
          toFieldPath: "spec.forProvider.namespace"
        - fromFieldPath: "spec.parameters.username"
          toFieldPath: "spec.forProvider.values.auth.username"
        - fromFieldPath: "spec.parameters.password"
          toFieldPath: "spec.forProvider.values.auth.password"
        - fromFieldPath: "spec.parameters.database"
          toFieldPath: "spec.forProvider.values.auth.database"
        - fromFieldPath: "spec.parameters.storage"
          toFieldPath: "spec.forProvider.values.primary.persistence.size"
