apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: databases.example.org
spec:
  group: example.org
  names:
    kind: Database
    plural: databases
  claimNames:
    kind: Database
    plural: databases
  defaultCompositionRef:
    name: mariadbcomposition
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                storage:
                  type: string
                  default: 1Gi
                username:
                  type: string
                  default: drupal
                password:
                  type: string
                  default: drupalpass
                database:
                  type: string
                  default: drupal
              required:
                - username
                - password
                - database
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mariadbcomposition
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: Database
  mode: Pipeline
  pipeline:
    - step: render-helmrelease
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: helm.crossplane.io/v1beta1
            kind: Release
            metadata:
              name: mariadb
              namespace: {{ .observed.composite.resource.metadata.namespace }}
            spec:
              forProvider:
                chart:
                  name: mariadb
                  repository: https://charts.bitnami.com/bitnami
                  version: "14.1.0"
                namespace: {{ .observed.composite.resource.metadata.namespace }}
                values:
                  auth:
                    rootPassword: rootpass
                    username: {{ .observed.composite.resource.spec.username }}
                    password: {{ .observed.composite.resource.spec.password }}
                    database: {{ .observed.composite.resource.spec.database }}
                  primary:
                    persistence:
                      size: {{ .observed.composite.resource.spec.storage }}
    - step: set-ready
      functionRef:
        name: crossplane-contrib-function-auto-ready
---
apiVersion: example.org/v1alpha1
kind: Database
metadata:
  name: drupal-db
  namespace: drupal-app
spec:
  storage: 1Gi
  username: drupal
  password: drupalpass
  database: drupal
