apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.16.0
---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: in-cluster-helm
spec:
  credentials:
    source: None
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: mariadbinstances.database.mycompany.io
spec:
  group: database.mycompany.io
  names:
    kind: MariaDBInstance
    plural: mariadbinstances
  claimNames:
    kind: MariaDBInstance
    plural: mariadbinstances
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    version:
                      type: string
                    size:
                      type: string
                    database:
                      type: string
                    username:
                      type: string
                    password:
                      type: string
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mariadbinstance-composition
spec:
  compositeTypeRef:
    apiVersion: database.mycompany.io/v1alpha1
    kind: MariaDBInstance
  resources:
    - name: mariadb
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: mariadb
          namespace: crossplane-system
        spec:
          providerConfigRef:
            name: in-cluster-helm
          forProvider:
            namespace: mariadb-ns
            chart:
              repository: https://charts.bitnami.com/bitnami
              name: mariadb
              version: 12.3.0
            values:
              image:
                repository: bitnami/mariadb
              primary:
                persistence:
                  enabled: true
                  size: 8Gi
              auth:
                rootPassword: root
                database: exampledb
                username: user
                password: pass
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.version
          toFieldPath: spec.forProvider.values.image.tag
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.database
          toFieldPath: spec.forProvider.values.auth.database
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.username
          toFieldPath: spec.forProvider.values.auth.username
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.password
          toFieldPath: spec.forProvider.values.auth.password
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.size
          toFieldPath: spec.forProvider.values.primary.persistence.size
          policy:
            fromFieldPath: Optional
---
