apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: mariadbinstances.database.mycompany.io
spec:
  group: database.mycompany.io
  names:
    kind: MariaDBInstance
    plural: mariadbinstances
  claimNames:
    kind: MariaDBInstance
    plural: mariadbinstances
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    version:
                      type: string
                    storageSize:
                      type: string
                    user:
                      type: string
                    password:
                      type: string
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mariadbinstance-composition
spec:
  compositeTypeRef:
    apiVersion: database.mycompany.io/v1alpha1
    kind: MariaDBInstance
  mode: Pipeline
  pipeline:
    - step: generate-password
      functionRef:
        name: function-random
      input:
        apiVersion: fn.crossplane.io/v1beta1
        kind: Input
        parameters:
          key: password
          length: 16

    - step: deploy-mariadb
      functionRef:
        name: function-apply
      input:
        apiVersion: fn.crossplane.io/v1beta1
        kind: Input
        resources:
          - apiVersion: helm.crossplane.io/v1beta1
            kind: Release
            metadata:
              name: mariadb-release
              namespace: database-namespace
            spec:
              providerConfigRef:
                name: example-helm-config
              forProvider:
                chart:
                  name: mariadb
                  repository: https://charts.bitnami.com/bitnami
                  version: 12.3.0
                namespace: mariadb-ns
                values:
                  image:
                    repository: bitnami/mariadb
                    tag: "10.6.12"
                  auth:
                    rootPassword: $(password)
                    database: exampledb
                    username: exampleuser
                  persistence:
                    enabled: true
                    size: 8Gi
---
apiVersion: database.mycompany.io/v1alpha1
kind: MariaDBInstance
metadata:
  name: dev-mariadb
spec:
  parameters:
    version: "10.6"
    storageSize: "8Gi"
    user: devuser
