apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: databases.example.org
spec:
  group: example.org
  names:
    kind: Database
    plural: databases
  claimNames:
    kind: Database
    plural: databases
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                storage:
                  type: string
                  default: 1Gi
                username:
                  type: string
                  default: drupal
                password:
                  type: string
                  default: drupalpass
                database:
                  type: string
                  default: drupal
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mariadbcomposition
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: Database
  mode: Pipeline
  pipeline:
    - step: render-mariadb
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: helm.crossplane.io/v1beta1
            kind: Release
            metadata:
              name: mariadb
              namespace: {{ .observed.composite.resource.metadata.namespace }}
            spec:
              forProvider:
                chart:
                  name: mariadb
                  repository: https://charts.bitnami.com/bitnami
                  version: "12.3.0"
                namespace: {{ .observed.composite.resource.metadata.namespace }}
                values:
                  image:
                    repository: bitnamilegacy/external-dns
                  auth:
                    rootPassword: rootpass
                    username: {{ .observed.composite.resource.spec.parameters.username }}
                    password: {{ .observed.composite.resource.spec.parameters.password }}
                    database: {{ .observed.composite.resource.spec.parameters.database }}
                  primary:
                    persistence:
                      size: {{ .observed.composite.resource.spec.parameters.storage }}
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
