apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.example.org
spec:
  group: example.org
  names:
    kind: XDatabase
    plural: xdatabases
  claimNames:
    kind: Database
    plural: databases
  defaultCompositionRef:
    name: mariadbcomposition
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                storage:
                  type: string
                  default: "1Gi"
                dbName:
                  type: string
                  default: "drupal"
                user:
                  type: string
                  default: "drupal"
                password:
                  type: string
                  default: "drupalpass"
              required: ["dbName", "user", "password"]
            status:
              type: object
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mariadbcomposition
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XDatabase
  mode: Pipeline
  pipeline:
    - step: create-secret
      functionRef:
        name: drupal-app-externaldb
      input:
        stringData:
          root-password: rootpass
          username: drupal
          password: drupalpass
          database: drupal

    - step: create-mariadb
      functionRef:
        name: crossplane-contrib-function-kubernetes-apply
      input:
        manifests:
          - apiVersion: apps/v1
            kind: StatefulSet
            metadata:
              name: mariadb
              namespace: drupal
              labels:
                app: mariadb
            spec:
              selector:
                matchLabels:
                  app: mariadb
              serviceName: mariadb
              replicas: 1
              template:
                metadata:
                  labels:
                    app: mariadb
                spec:
                  containers:
                    - name: mariadb
                      image: mariadb:11.3
                      ports:
                        - containerPort: 3306
                          name: mysql
                      env:
                        - name: MYSQL_ROOT_PASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: mariadb-secret
                              key: root-password
                        - name: MYSQL_DATABASE
                          valueFrom:
                            secretKeyRef:
                              name: mariadb-secret
                              key: database
                        - name: MYSQL_USER
                          valueFrom:
                            secretKeyRef:
                              name: mariadb-secret
                              key: username
                        - name: MYSQL_PASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: mariadb-secret
                              key: password
                      volumeMounts:
                        - name: data
                          mountPath: /var/lib/mysql
              volumeClaimTemplates:
                - metadata:
                    name: data
                  spec:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 1Gi
          - apiVersion: v1
            kind: Service
            metadata:
              name: mariadb
              namespace: drupal
              labels:
                app: mariadb
            spec:
              ports:
                - port: 3306
                  targetPort: mysql
              selector:
                app: mariadb
          - apiVersion: v1
            kind: Secret
            metadata:
              name: mariadb-secret
              namespace: drupal
            stringData:
              root-password: rootpass
              username: drupal
              password: drupalpass
              database: drupal
