# -----------------------------------------------------
# 1. Provider: Helm
# -----------------------------------------------------
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-contrib-provider-helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v1.0.2
---
apiVersion: apiextensions.crossplane.io/v1beta1
kind: CompositeResourceDefinition
metadata:
  name: mariadbinstances.database.mycompany.io
spec:
  group: database.mycompany.io
  names:
    kind: MariaDBInstance
    plural: mariadbinstances
  claimNames:
    kind: MariaDBInstance
    plural: mariadbinstances
  defaultCompositionRef:
    name: mariadbinstance-composition
  connectionSecretKeys:
    - username
    - password
    - endpoint
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    version:
                      type: string
                    size:
                      type: string
                    database:
                      type: string
                    username:
                      type: string
                    password:
                      type: string
---
# -----------------------------------------------------
# 4. Composition (uses Helm provider only)
# -----------------------------------------------------
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mariadbinstance-composition
spec:
  compositeTypeRef:
    apiVersion: database.mycompany.io/v1alpha1
    kind: MariaDBInstance
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - name: mariadb
      base:
        apiVersion: helm.crossplane.io/v1
        kind: Release
        metadata:
          namespace: crossplane-system
        spec:
          providerConfigRef:
            name: in-cluster-helm
          forProvider:
            namespace: mariadb-ns
            chart:
              repository: https://charts.bitnami.com/bitnami
              name: mariadb
              version: 12.3.0
            values:
              image:
                repository: bitnami/mariadb
              primary:
                persistence:
                  enabled: true
                  size: 8Gi
              auth:
                rootPassword: root
                database: defaultdb
                username: user
                password: pass
          writeConnectionSecretToRef:
            namespace: crossplane-system
            name: mariadb-conn
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.version
          toFieldPath: spec.forProvider.values.image.tag
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.database
          toFieldPath: spec.forProvider.values.auth.database
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.username
          toFieldPath: spec.forProvider.values.auth.username
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.password
          toFieldPath: spec.forProvider.values.auth.password
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.size
          toFieldPath: spec.forProvider.values.primary.persistence.size
          policy:
            fromFieldPath: Optional
---
# -----------------------------------------------------
# 5. Example Claim (developer request)
# -----------------------------------------------------
apiVersion: database.mycompany.io/v1alpha1
kind: MariaDBInstance
metadata:
  name: dev-db
spec:
  parameters:
    version: "10.6.12"
    database: "appdb"
    username: "appuser"
    password: "SuperSecret123"
    size: "8Gi"