apiVersion: database.mycompany.io/v1alpha1
kind: MariaDBInstance
metadata:
  name: dev-mariadb
spec:
  parameters:
    version: "10.6.12"
    size: "8Gi"
    database: "devdb"
    username: "devuser"
    password: "SuperSecret!"
