apiVersion: database.mycompany.io/v1alpha1
kind: MariaDBInstance
metadata:
  name: dev-db
spec:
  parameters:
    version: "10.6"
    database: "appdb"
    username: "appuser"
    password: "SuperSecret123"
    size: "8Gi"
