apiVersion: example.org/v1alpha1
kind: Database
metadata:
  name: drupal-db
  namespace: drupal-app
spec:
  parameters:
    storage: 1Gi
    username: drupal
    password: drupalpass
    database: drupal
