apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpostgres-standard
  labels:
    provider: kind
spec:
  compositeTypeRef:
    apiVersion: platform.example.io/v1alpha1
    kind: XPostgres
  resources:
  - name: postgres-deployment
    base:
      apiVersion: apps/v1
      kind: Deployment
      spec:
        selector:
          matchLabels:
            app: postgres
            instance: managed-by-crossplane
        template:
          metadata:
            labels:
              app: postgres
              instance: managed-by-crossplane
          spec:
            containers:
            - name: postgres
              image: postgres:15-alpine
              env:
              - name: POSTGRES_PASSWORD
                value: supersecret
              ports:
              - containerPort: 5432