apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drupal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  revisionHistoryLimit: 5
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: drupal
      targetRevision: "23.0.0"
      helm:
        valueFiles:
        - $values/values.yaml
    - repoURL: https://github.com/qasmi/tdd-developer-platform-demo.git
      path: ./demo-cluster/dev/drupal
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
